sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ayfantis/movies-app -f Dockerfile.dev .

script:
  - docker run -e CI=true ayfantis/movies-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "movies-app"
  env: "Moviesapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-583762202529"
  bucket_path: "movies-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"